# Generated by Django 3.2.6 on 2021-08-27 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_company_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='starting_salary',
            field=models.IntegerField(default=1000),
            preserve_default=False,
        ),
    ]
