# Generated by Django 3.2.6 on 2021-08-30 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_auto_20210829_0250'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyApplicationForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placement_year', models.PositiveSmallIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('form_fields', models.TextField()),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.company')),
            ],
            options={
                'verbose_name_plural': 'Company Application Form',
            },
        ),
    ]
