# Generated by Django 3.2.6 on 2021-08-31 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_companyapplicationform'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CompanyApplicationForm',
            new_name='PlacementApplication',
        ),
        migrations.AlterModelOptions(
            name='placementapplication',
            options={'verbose_name_plural': 'Placement Application'},
        ),
    ]
