# Generated by Django 3.2.6 on 2021-08-31 08:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_auto_20210831_1304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placementapplication',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company', to='base.company'),
        ),
    ]
