# Generated by Django 3.2.6 on 2021-09-01 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_alter_placementapplication_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlacementApplicationResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('responsed_at', models.DateTimeField(auto_now=True)),
                ('responses', models.TextField()),
                ('placement_application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='placement_application', to='base.placementapplication')),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student', to='base.student')),
            ],
            options={
                'verbose_name_plural': 'Placement Application Response',
            },
        ),
    ]
