# Generated by Django 3.2.6 on 2021-09-01 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_placementapplicationresponse'),
    ]

    operations = [
        migrations.RenameField(
            model_name='placementapplicationresponse',
            old_name='responsed_at',
            new_name='responded_at',
        ),
    ]
