# Generated by Django 3.2.6 on 2021-09-02 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_rename_responsed_at_placementapplicationresponse_responded_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlacementApplicationResponseFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('files', models.TextField()),
                ('response_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='placement_application_response', to='base.placementapplicationresponse')),
            ],
            options={
                'verbose_name_plural': 'Placement Application Response Files',
            },
        ),
    ]
