# Generated by Django 3.2.6 on 2021-09-03 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_rename_response_id_placementapplicationresponsefiles_response'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='prn_number',
            new_name='roll_number',
        ),
    ]
