# Generated by Django 3.2.6 on 2021-09-19 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0022_alter_student_roll_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='day',
            field=models.CharField(choices=[('Day 0', 'Day 0'), ('Day 1', 'Day 1'), ('Day 2', 'Day 2')], default=2, max_length=25),
            preserve_default=False,
        ),
    ]
