# Generated by Django 3.2.6 on 2021-09-19 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0023_company_day'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='day',
        ),
    ]
