# Generated by Django 3.2.6 on 2021-09-19 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0024_remove_company_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='day',
            field=models.CharField(choices=[('Day 0', 'Day 0'), ('Day 1', 'Day 1'), ('Day 2', 'Day 2')], default='Day 0', max_length=25),
        ),
    ]
