# Generated by Django 3.2.6 on 2021-09-19 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0025_company_day'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlacementStatus',
            fields=[
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='base.student')),
                ('offers', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Placement Status',
            },
        ),
    ]
