# Generated by Django 3.2.6 on 2021-09-20 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0026_placementstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='placementstatus',
            name='day0_selected_company_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='placementstatus',
            name='day0_selected_company_salary',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='placementstatus',
            name='day1_selected_company_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='placementstatus',
            name='day1_selected_company_salary',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='placementstatus',
            name='day2_selected_company_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='placementstatus',
            name='day2_selected_company_salary',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='placementstatus',
            name='placed_company_day',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='placementstatus',
            name='placed_company_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='placementstatus',
            name='placed_company_salary',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
