# Generated by Django 3.2.6 on 2021-09-21 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0027_auto_20210920_2028'),
    ]

    operations = [
        migrations.AddField(
            model_name='placementstatus',
            name='placed_year',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
